---
# Configure Linux
- name: RedHat | Install required packages
  yum: name={{ item }} state=present
  with_items: "{{ rh.packages_depends }}"

#- name: Stop Firewall and Diable it
#  service: name=firewalld state=stopped enabled=no

- name: Diable SELinux policy
  selinux: state=disabled

# Create users and groups
- name: Create oracle group
  group: name={{ oracle_system_group }} state=present

- name: Add oracle extra groups
  group: name={{ item }} state=present
  with_items: "{{ oracle_extra_groups }}"

- name: Create oracle user
  user: name={{ oracle_system_user }} group={{ oracle_system_group }} password={{ oracle_system_user_password }}

- name: Get volume group name
  shell: vgs | awk  '{if (NR!=1) {print $1}}'
  register: storage_vg

- name: Create a logical volume on invalid volume group
  lvol:
    vg: "{{ storage_vg.stdout }}"
    lv: "{{ item }}"
    size: 10g
    state: present
    force: yes
  register: lvcreate
  become: yes
  with_items: "{{ storage_lvol }}"

- name: Determine the File System Type 
  shell: df -Th | grep "^/dev" |awk 'NR==1{print $2}'
  register: file_type

- name: make filesystems...
  filesystem:
    fstype: "{{ file_type.stdout }}"
    dev: "/dev/{{ storage_vg.stdout }}/{{ item }}"
  become: yes
  with_items: "{{ storage_lvol }}"

- name: create mount directories...
  file:
    path: "/{{ item }}"
    state: directory
    owner: "{{ oracle_system_user }}"
    group: "{{ oracle_system_group }}"
  become: yes
  with_items: "{{ storage_lvol }}"

- name: mount directories...
  mount:
    name: "/{{ item }}"
    src: "/dev/{{ storage_vg.stdout }}/{{ item }}"
    fstype: "{{ file_type.stdout }}"
    opts: defaults,relatime
    state: mounted
  become: yes
  with_items: "{{ storage_lvol }}"

- name: create mount directories...
  file:
    path: "/{{ item }}"
    state: directory
    owner: "{{ oracle_system_user }}"
    group: "{{ oracle_system_group }}"
  become: yes
  with_items: "{{ storage_lvol }}"

- name: Create Oracle Base directory
  file: state=directory path={{ oracle_base_dir }} owner={{ oracle_system_user }} group={{ oracle_system_group }}

- name: Add oracle extra groups
  user: name={{ oracle_system_user }} groups={{ item }} append=yes
  with_items: "{{ oracle_extra_groups }}"

- name: Add oracle user limits
  lineinfile: dest=/etc/security/limits.conf line="{{ oracle_system_user }} {{ item.limit }} {{ item.type}} {{ item.value }}"
  with_items: "{{ sys_config.limits }}"

# Disable transparent hugepages
- name: Copy script to disable transparent hugepages
  copy: src=disable_trans_hugepages.sh dest='/tmp/disable_trans_hugepages.sh' mode=755

- name: Disable Transparent Huge Pages
  shell: '/tmp/disable_trans_hugepages.sh'

- name: Remove the script
  file: path='/tmp/disable_trans_hugepages.sh' state=absent

- name: Configure kernel for hugepages
  sysctl: name='vm.nr_hugepages' value="{{ sys_config.hugepages_nr }}" state=present
